name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NodeJs install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Code style check
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Deploy
        run: echo "Deploy to Server"

